### ISSUE TITLE
Peerweb falls over for large websites

### ISSUE THREAD

**Issue by retrohacker** [retrohacker/peerweb2.0#11]
Large websites (like those generated with jekyll) break peerweb

**Comment by phoenix1796** [comment]
Hey , I was just testing a site and saw that  the Download logs appear multiple time for the same website page , and from what i could see , due to the code queuing a new torrent for each "file" request even inside the webpage , although this doesn't result in re-download , but when loading a big site this maybe the reason that the peerweb breaks .

P.S. What i mean is that the protocol handler code may need to be re-thought of ,so that it doesn't try to download the whole torrent once more for "every" request .

**Comment by retrohacker** [comment]
Yes, this is rather silly code on my part. It delegates the caching of files to the webtorrent client.

Regardless of whether this is what is breaking electron's protocol handler, it needs to be fixed before upgrading to the latest version of webtorrent. Webtorrent now errors when re-adding a torrent that already exists.

The other thing I notice is that, on websites that fail, there are urls to the normal web that don't include a protocol, so my protocol handles them. I.E. `analytics.google.com`.

**Comment by retrohacker** [comment]
A few theories to test this evening when I get off work.

**Comment by retrohacker** [comment]
This appears to have fixed it

https://github.com/retrohacker/peerweb/commit/acfdfdd058410b3ac82668e913ec7ac8c693c87e

**Comment by retrohacker** [comment]
Hey @phoenix1796, saw you on IRC this morning. Sorry I was AFK while you were on!
