### ISSUE TITLE
Pass protocol relative `http` requests on through

### ISSUE THREAD

**Issue by retrohacker** [retrohacker/peerweb2.0#14]
I'm not sure what the best way of doing this is yet, but we need to let protocol-less requests meant for `http` pass through peerweb. Perhaps something as simple as testing if the url is a valid magnet uri or torrent hash and letting it pass through otherwise?

**Comment by phoenix1796** [comment]
can we pass the request to the default http handler from the custom "peer://" protocol handler ?

**Comment by retrohacker** [comment]
I'm unsure. I know you can pass back custom error numbers for requests
(I.e. 304), but I haven't tried using that to redirect the browser request.

**Comment by phoenix1796** [comment]
You can pass the error codes , but as far as their docs can tell , the error code can't be used for redirecting of any kind both due to no additional parameters and due to the fact that external URLs in the page also have the torrent hash before them.
So , my guess is we need to write some custom code using fetch or other such api which can atleast handle basic requests to servers

**Comment by retrohacker** [comment]
This needs a bit more thought.

This may be something we can land upstream with the electron project.

When a torrent page contains links to documents outside the torrent (or, specifically, outside the peer:// network), we would need some sort of warning as the HTTP content isn't dependable over time (dns changes, servers fail, etc.) while the torrent is forever.

**Comment by retrohacker** [comment]
Tracking this here: https://github.com/electron/electron/issues/6582

**Comment by retrohacker** [comment]
Moved to https://github.com/electron/electron/issues/6582
